music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, uniqueness:true, presence:true
end

music_app/app/models/user.rb
class User < ApplicationRecord

    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }
  
    before_validation :ensure_session_token

    attr_reader :password

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
    
        if user && user.is_password?(password)
          user
        else
          nil
        end
        
    end
    
    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end
    

    def generate_unique_session_token
        loop do 
            session_token = SecureRandom::urlsafe_base64(6)
            return session_token unless User.exists?(session_token: session_token)
        end
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end

    def reset_session_token
        self.session_token = SecureRandom::urlsafe_base64(6)
        self.save!
        self.session_token
    end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user
        return nil unless session[:session_token]
        @current_user = User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        @current_user = user
        session[:session_token] = user.reset_session_token
    end

    def logout!
        current_user.try(:reset_session_token)
        session[:session_token] = nil
    end


end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :set_band, only: [:show, :edit, :update, :destroy]
    def index
        @bands = Band.all
        render :index
    end
    def new
        @band = Band.new
    end
    def create
        @band = Band.new(band_params)
        if @band.save!
            redirect_to band_url(@band.id)
        else    
            flash[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def edit
        render :edit
    end
    def show
       render :show if set_band
        
    end

    def update
        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        set_band.destroy
        redirect_to bands_url
    end

    def band_params
        params.require(:bands).permit(:name)
    end

    def set_band
        @band = Band.find(params[:id])
        # redirect_to bands_url
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
        if @user 
            login!(@user)
            redirect_to user_url(@user.id)
        else
            flash.now[:errors] = ['Incorrect email/password!']
            render :new
        end
    end

    def new
        @user = User.new
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

    

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save!
            render :show
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:email,:password)
    end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/bands/edit.html.erb
<form  action = "<%= band_url(@band.id) %>" method = 'post'>
<input type="hidden" name="_method" value= "PATCH" >
 <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

    <label> name
        <input type= "text" name = 'bands[name]' value = <%= @band.name%> >
    </label>


    <input type= 'submit' value = "Edit band">

</form>

music_app/app/views/bands/index.html.erb
<h1> Band's List</h1>
<%  @bands.each do |band| %>
<li><%= band.name %></li>
<% end %>

music_app/app/views/bands/new.html.erb
<form  action = "<%= bands_url %>" method = 'post'>
 <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

    <label> name
        <input type= "text" name = 'bands[name]' value = <%= @band.name%> >
    </label>


    <input type= 'submit' value = "Add band">

</form>

music_app/app/views/bands/show.html.erb
<h1> Show Band  </h1>
<li><%= @band.name %></li>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="style.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
        <h1> Music App </h1>
    </header> 


    <% if logged_in? %>
        <form action="<%= session_url %>" method='post'>
            <input type="hidden" name="_method" value='delete'>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="submit" value='Logout'>
        </form>
    <% else %>
      <a href="<%= new_user_url%>">Sign Up</a>
      <a href="<%= new_session_url %>">Log In</a>
    <% end %>
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <%= error %>
        <% end %>
      <% end %>


      <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<form  action = "<%= users_url %>" method = 'post'>
 <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

    <label> email
        <input type= "text" name = 'user[email]' value = <%= @user.email%> >
    </label>

    <label> password
        <input type= "password" name = 'user[password]' >
    </label>

    <input type= 'submit' value = "Sign Up">

</form>

music_app/app/views/users/show.html.erb
<h1> Hello <%= current_user.email %> </h1>